/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuarantineRouteImport } from './routes/_authenticated/quarantine'
import { Route as AuthenticatedPostTweetRouteImport } from './routes/_authenticated/post-tweet'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedMassEngageRouteImport } from './routes/_authenticated/mass-engage'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as AuthenticatedEditAccountsRouteImport } from './routes/_authenticated/edit-accounts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations.index'
import { Route as AuthenticatedAutomationsBuilderIndexRouteImport } from './routes/_authenticated/automations.builder.index'
import { Route as ApiPublicHooksSessionKeepaliveRouteImport } from './routes/api/public/hooks/session-keepalive'
import { Route as ApiPublicHooksRunQueueRouteImport } from './routes/api/public/hooks/run-queue'
import { Route as ApiPublicHooksEducationRouteImport } from './routes/api/public/hooks/education'
import { Route as ApiPublicHooksCollectViewsRouteImport } from './routes/api/public/hooks/collect-views'
import { Route as AuthenticatedAutomationsBuilderIdRouteImport } from './routes/_authenticated/automations.builder.$id'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuarantineRoute = AuthenticatedQuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostTweetRoute = AuthenticatedPostTweetRouteImport.update({
  id: '/post-tweet',
  path: '/post-tweet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMassEngageRoute = AuthenticatedMassEngageRouteImport.update({
  id: '/mass-engage',
  path: '/mass-engage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditAccountsRoute =
  AuthenticatedEditAccountsRouteImport.update({
    id: '/edit-accounts',
    path: '/edit-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const AuthenticatedAutomationsBuilderIndexRoute =
  AuthenticatedAutomationsBuilderIndexRouteImport.update({
    id: '/builder/',
    path: '/builder/',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)
const ApiPublicHooksSessionKeepaliveRoute =
  ApiPublicHooksSessionKeepaliveRouteImport.update({
    id: '/api/public/hooks/session-keepalive',
    path: '/api/public/hooks/session-keepalive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunQueueRoute = ApiPublicHooksRunQueueRouteImport.update({
  id: '/api/public/hooks/run-queue',
  path: '/api/public/hooks/run-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEducationRoute = ApiPublicHooksEducationRouteImport.update({
  id: '/api/public/hooks/education',
  path: '/api/public/hooks/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCollectViewsRoute =
  ApiPublicHooksCollectViewsRouteImport.update({
    id: '/api/public/hooks/collect-views',
    path: '/api/public/hooks/collect-views',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAutomationsBuilderIdRoute =
  AuthenticatedAutomationsBuilderIdRouteImport.update({
    id: '/builder/$id',
    path: '/builder/$id',
    getParentRoute: () => AuthenticatedAutomationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edit-accounts': typeof AuthenticatedEditAccountsRoute
  '/education': typeof AuthenticatedEducationRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/mass-engage': typeof AuthenticatedMassEngageRoute
  '/media': typeof AuthenticatedMediaRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/post-tweet': typeof AuthenticatedPostTweetRoute
  '/quarantine': typeof AuthenticatedQuarantineRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/automations/builder/$id': typeof AuthenticatedAutomationsBuilderIdRoute
  '/api/public/hooks/collect-views': typeof ApiPublicHooksCollectViewsRoute
  '/api/public/hooks/education': typeof ApiPublicHooksEducationRoute
  '/api/public/hooks/run-queue': typeof ApiPublicHooksRunQueueRoute
  '/api/public/hooks/session-keepalive': typeof ApiPublicHooksSessionKeepaliveRoute
  '/automations/builder/': typeof AuthenticatedAutomationsBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/edit-accounts': typeof AuthenticatedEditAccountsRoute
  '/education': typeof AuthenticatedEducationRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/mass-engage': typeof AuthenticatedMassEngageRoute
  '/media': typeof AuthenticatedMediaRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/post-tweet': typeof AuthenticatedPostTweetRoute
  '/quarantine': typeof AuthenticatedQuarantineRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/automations/builder/$id': typeof AuthenticatedAutomationsBuilderIdRoute
  '/api/public/hooks/collect-views': typeof ApiPublicHooksCollectViewsRoute
  '/api/public/hooks/education': typeof ApiPublicHooksEducationRoute
  '/api/public/hooks/run-queue': typeof ApiPublicHooksRunQueueRoute
  '/api/public/hooks/session-keepalive': typeof ApiPublicHooksSessionKeepaliveRoute
  '/automations/builder': typeof AuthenticatedAutomationsBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRouteWithChildren
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/edit-accounts': typeof AuthenticatedEditAccountsRoute
  '/_authenticated/education': typeof AuthenticatedEducationRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/mass-engage': typeof AuthenticatedMassEngageRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/post-tweet': typeof AuthenticatedPostTweetRoute
  '/_authenticated/quarantine': typeof AuthenticatedQuarantineRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/automations/builder/$id': typeof AuthenticatedAutomationsBuilderIdRoute
  '/api/public/hooks/collect-views': typeof ApiPublicHooksCollectViewsRoute
  '/api/public/hooks/education': typeof ApiPublicHooksEducationRoute
  '/api/public/hooks/run-queue': typeof ApiPublicHooksRunQueueRoute
  '/api/public/hooks/session-keepalive': typeof ApiPublicHooksSessionKeepaliveRoute
  '/_authenticated/automations/builder/': typeof AuthenticatedAutomationsBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending'
    | '/accounts'
    | '/admin'
    | '/automations'
    | '/communities'
    | '/dashboard'
    | '/edit-accounts'
    | '/education'
    | '/logs'
    | '/mass-engage'
    | '/media'
    | '/monitoring'
    | '/post-tweet'
    | '/quarantine'
    | '/automations/'
    | '/automations/builder/$id'
    | '/api/public/hooks/collect-views'
    | '/api/public/hooks/education'
    | '/api/public/hooks/run-queue'
    | '/api/public/hooks/session-keepalive'
    | '/automations/builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/accounts'
    | '/admin'
    | '/communities'
    | '/dashboard'
    | '/edit-accounts'
    | '/education'
    | '/logs'
    | '/mass-engage'
    | '/media'
    | '/monitoring'
    | '/post-tweet'
    | '/quarantine'
    | '/automations'
    | '/automations/builder/$id'
    | '/api/public/hooks/collect-views'
    | '/api/public/hooks/education'
    | '/api/public/hooks/run-queue'
    | '/api/public/hooks/session-keepalive'
    | '/automations/builder'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pending'
    | '/_authenticated/accounts'
    | '/_authenticated/admin'
    | '/_authenticated/automations'
    | '/_authenticated/communities'
    | '/_authenticated/dashboard'
    | '/_authenticated/edit-accounts'
    | '/_authenticated/education'
    | '/_authenticated/logs'
    | '/_authenticated/mass-engage'
    | '/_authenticated/media'
    | '/_authenticated/monitoring'
    | '/_authenticated/post-tweet'
    | '/_authenticated/quarantine'
    | '/_authenticated/automations/'
    | '/_authenticated/automations/builder/$id'
    | '/api/public/hooks/collect-views'
    | '/api/public/hooks/education'
    | '/api/public/hooks/run-queue'
    | '/api/public/hooks/session-keepalive'
    | '/_authenticated/automations/builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  ApiPublicHooksCollectViewsRoute: typeof ApiPublicHooksCollectViewsRoute
  ApiPublicHooksEducationRoute: typeof ApiPublicHooksEducationRoute
  ApiPublicHooksRunQueueRoute: typeof ApiPublicHooksRunQueueRoute
  ApiPublicHooksSessionKeepaliveRoute: typeof ApiPublicHooksSessionKeepaliveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quarantine': {
      id: '/_authenticated/quarantine'
      path: '/quarantine'
      fullPath: '/quarantine'
      preLoaderRoute: typeof AuthenticatedQuarantineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-tweet': {
      id: '/_authenticated/post-tweet'
      path: '/post-tweet'
      fullPath: '/post-tweet'
      preLoaderRoute: typeof AuthenticatedPostTweetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mass-engage': {
      id: '/_authenticated/mass-engage'
      path: '/mass-engage'
      fullPath: '/mass-engage'
      preLoaderRoute: typeof AuthenticatedMassEngageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-accounts': {
      id: '/_authenticated/edit-accounts'
      path: '/edit-accounts'
      fullPath: '/edit-accounts'
      preLoaderRoute: typeof AuthenticatedEditAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/_authenticated/automations/builder/': {
      id: '/_authenticated/automations/builder/'
      path: '/builder'
      fullPath: '/automations/builder/'
      preLoaderRoute: typeof AuthenticatedAutomationsBuilderIndexRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
    '/api/public/hooks/session-keepalive': {
      id: '/api/public/hooks/session-keepalive'
      path: '/api/public/hooks/session-keepalive'
      fullPath: '/api/public/hooks/session-keepalive'
      preLoaderRoute: typeof ApiPublicHooksSessionKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-queue': {
      id: '/api/public/hooks/run-queue'
      path: '/api/public/hooks/run-queue'
      fullPath: '/api/public/hooks/run-queue'
      preLoaderRoute: typeof ApiPublicHooksRunQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/education': {
      id: '/api/public/hooks/education'
      path: '/api/public/hooks/education'
      fullPath: '/api/public/hooks/education'
      preLoaderRoute: typeof ApiPublicHooksEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/collect-views': {
      id: '/api/public/hooks/collect-views'
      path: '/api/public/hooks/collect-views'
      fullPath: '/api/public/hooks/collect-views'
      preLoaderRoute: typeof ApiPublicHooksCollectViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automations/builder/$id': {
      id: '/_authenticated/automations/builder/$id'
      path: '/builder/$id'
      fullPath: '/automations/builder/$id'
      preLoaderRoute: typeof AuthenticatedAutomationsBuilderIdRouteImport
      parentRoute: typeof AuthenticatedAutomationsRoute
    }
  }
}

interface AuthenticatedAutomationsRouteChildren {
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
  AuthenticatedAutomationsBuilderIdRoute: typeof AuthenticatedAutomationsBuilderIdRoute
  AuthenticatedAutomationsBuilderIndexRoute: typeof AuthenticatedAutomationsBuilderIndexRoute
}

const AuthenticatedAutomationsRouteChildren: AuthenticatedAutomationsRouteChildren =
  {
    AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
    AuthenticatedAutomationsBuilderIdRoute:
      AuthenticatedAutomationsBuilderIdRoute,
    AuthenticatedAutomationsBuilderIndexRoute:
      AuthenticatedAutomationsBuilderIndexRoute,
  }

const AuthenticatedAutomationsRouteWithChildren =
  AuthenticatedAutomationsRoute._addFileChildren(
    AuthenticatedAutomationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRouteWithChildren
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEditAccountsRoute: typeof AuthenticatedEditAccountsRoute
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMassEngageRoute: typeof AuthenticatedMassEngageRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedPostTweetRoute: typeof AuthenticatedPostTweetRoute
  AuthenticatedQuarantineRoute: typeof AuthenticatedQuarantineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRouteWithChildren,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEditAccountsRoute: AuthenticatedEditAccountsRoute,
  AuthenticatedEducationRoute: AuthenticatedEducationRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMassEngageRoute: AuthenticatedMassEngageRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedPostTweetRoute: AuthenticatedPostTweetRoute,
  AuthenticatedQuarantineRoute: AuthenticatedQuarantineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  ApiPublicHooksCollectViewsRoute: ApiPublicHooksCollectViewsRoute,
  ApiPublicHooksEducationRoute: ApiPublicHooksEducationRoute,
  ApiPublicHooksRunQueueRoute: ApiPublicHooksRunQueueRoute,
  ApiPublicHooksSessionKeepaliveRoute: ApiPublicHooksSessionKeepaliveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
